INSERT INTO promotion (PROMO_CODE, BOOK_TYPE, PERCENT) VALUES ('PRED10','EDUCATIONAL',10);
INSERT INTO promotion (PROMO_CODE, BOOK_TYPE, PERCENT) VALUES ('PRFC20','FICTION',20);
INSERT INTO promotion (PROMO_CODE, BOOK_TYPE, PERCENT) VALUES ('PRCO30','COMIC',30);